### ISSUE TITLE
Automatically detect session timeout when api endpoint returns 403

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#104]

**Comment by Gerviba** [comment]
it's on `feature/backend`

**Comment by berenteb** [comment]
AuthContext will detect it when the page loads. How about that? I implemented some kind of 403 handling (when the axios catches an error, a toast is generated to notify the user and the loggedIn state is unset)

**Comment by berenteb** [comment]
I was about to write about this anyways

**Comment by berenteb** [comment]
closed by #79
