### ISSUE TITLE
Create an Impressum page

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#121]
- Add a link to the footer called 'Impresszum'
- Impresszum page:
  - Header: Impresszum
  - "A Gólyakörte 2022 weblapját az SSSL megbízásából a [Kir-Dev] (kir-dev.sch) [italics]:"speed-run munkasoport" készítette."
  - List all the contributors: "Fejlesztők"
    - Schámi, kir-dev profile picture, tags: [Project Leader, Backend]
    - etc...
  - "Felhasznált technológiák: Kotlin, Spring-boot, Typescript és React. Mint ahogy az összes többi projektünk ez is [nyílt forráskódú] (git url)! Ha kérdésed van vagy érdekel a többi projektünk is, látogass el az [oldalunkra] (kir-dev site) vagy keress fel minket a Kir-Dev standnál!"
  - "Az alaklamazás a KSZK Kubernetes clusterjében fut, köszönjük az erőforrást és a segítséget nekik ezúton is!"

**Comment by poiuztrewq1** [comment]
Adom
