### ISSUE TITLE
Global style

### ISSUE THREAD

**Issue by berenteb** [kir-dev/cmsch#132]
- ColorScheme color in dark mode is too bright
- White is too bright in dark mode -> gray.500 or similar.
- Margins

**Comment by tomitheninja** [comment]
Chrome has an error reporting tool (lighthouse) built in, which can detect low contrast issues.

Follow right click > inspect element > lighthouse to access it

**Comment by berenteb** [comment]
Yeah but you can spend a whole day with those. Although I forgot that tool, but I don't think we have the full capacity to fix those issues.
