### ISSUE TITLE
SVG background

### ISSUE THREAD

**Issue by berenteb** [kir-dev/cmsch#140]
Generate SVG background with bgjar. Remove background from that SVG!
@Gerviba since you had the idea please generate the background you like, and we will include it!

**Comment by Gerviba** [comment]
Add some green and/or gray circles, optionally with gradient. Show them only if the screen is wide enough and place the circles to the edge. Sg like the moon template from bgjar.

**Comment by berenteb** [comment]
Due to the higher demand for the mobile view, this is a low priority issue. Closing now to clear out issues.
