### ISSUE TITLE
Handle achivements that are not availble currently

### ISSUE THREAD

**Issue by SepsiLaszlo** [kir-dev/cmsch#156]
Achivement API provides the availableFrom and availableTo attributes whic specifies the range where the achivement can be submitted.
Should the front-end provide an indication if an achivemnet is out of this range, or this will not be relevant for this iteration?

@Gerviba, @berenteb  what do you think?

**Comment by berenteb** [comment]
Since this is a one day event, I think it is irrelevant for now.

**Comment by Gerviba** [comment]
The ones that are not available are not shown. So I guess he availableTo might be a good idea to show.

**Comment by Tschonti** [comment]
infobox maybe...
