### ISSUE TITLE
New background color proposals 

### ISSUE THREAD

**Issue by tomitheninja** [kir-dev/cmsch#163]
Very dark navy blue
```css
body.chakra-ui-dark { --chakra-colors-gray-900: #0f172a; }
```
The other value I found while playing with the sliders
```css
body.chakra-ui-dark { --chakra-colors-gray-900: hsl(222deg 47% 10%); }
```

In my opinion these bgcolors are nicer than the default gray-900, but I think we should have a discussion about it.

**Comment by triszt4n** [comment]
Wow these are wirklich nice, we should really consider changing the gray scale in customTheme a bit

**Comment by berenteb** [comment]
This hasn't been talked about, closing now. Reopen if needed.
