### ISSUE TITLE
Information dropdown navitem

### ISSUE THREAD

**Issue by berenteb** [kir-dev/cmsch#173]
Link to:
- maps
- schedule

**Comment by berenteb** [comment]
React Router does not support hash links natively. Will come back to it, because it neads an overview of the whole navigation bar.

**Comment by triszt4n** [comment]
You can create some extra pages with the same content (`/map`, `/schedule` easy as that)

**Comment by berenteb** [comment]
# links does not redirect, so router is not needed.

**Comment by berenteb** [comment]
Nav item has not been created, there are links on the home page. This is due to redirect avoidance.
