### ISSUE TITLE
Create prompt to select group

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#188]
Backend will provide a bool on `/profile` or whenver you want, called `groupSelectionAllowed`, a map called `availableGroups` (containing group ids and names), and a `fallbackGroup` with the id of the fallback group.

for example:
```
{
...
  "groupSelectionAllowed": true,
  "availableGroups": {
    12:  "I02",
    631: "BPI03",
    9:   "I_IMSc3",
    80:  "vendég"
  },
  "fallbackGroup": 80
...
}
```

If the bool is true:
 - Prompt a user a message: "Állítsd be a tankörödet, hogy részt vehess a feladatokban!" next line: "Csak helyesen beállított tankörrel fog érvényesülni a tanköri jelenlét!"
 - A dropdown to select from the list of the groups (there are approx. 40 of them)
 - "Beállít" (select selected group), "Vendég vagyok" (select fallback group), "Mégse"
 - Do not allow to open any "feladatok" menu with `groupSelectionAllowed = true`
 - Use `POST /api/group/select/{groupId}` to select group id (edit: the path is group, not groups)
   - response: `{"status":"OK"}` or `{"status":"INVALID_GROUP"}` (not existing group) or `{"status":"LEAVE_DENIED"}` (group cannot be leaved) or `{"status":"UNAUTHORIZED"}`

If false: Ignore the prompt

**Comment by berenteb** [comment]
Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]

**Comment by berenteb** [comment]
I might not understand this feature. Please talk about it soon.
