### ISSUE TITLE
ref(ui): Vectorize logos

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/cmsch#216]
## Idea:

Make svgs from logos provided as psd files yet (make export)

**Comment by Gerviba** [comment]
Psd is a rasterized format, it cannot be exported to vector images.
Use the png to (auto) trace them using Adobe Illustrator or Inkscape.
https://www.stickermule.com/blog/how-to-use-image-trace-in-adobe-illustrator

**Comment by berenteb** [comment]
webp would be better, SEO prefers it (I know we don't optimize that much) (?)

**Comment by SzaboKolos** [comment]
Here are the svg for the page, if you need any edits for them find me.
[golyakorteSVGs.zip](https://github.com/kir-dev/cmsch/files/8102705/golyakorteSVGs.zip)
