### ISSUE TITLE
PizzáSCH website

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/cmsch#229]
https://github.com/kir-dev/cmsch/blob/55b69d05618fa9507020220b5da500a7fc6b11ba/src/main/client/src/content/communities.ts#L648

Should it not be: `https://schpincer.sch.bme.hu/provider/pizzasch`?

Please have a look at all the other schpincér sites like lángosch, vödör etc.

**Comment by triszt4n** [comment]
@Gerviba what do you think abuot this?

**Comment by Gerviba** [comment]
hm, they sent us these urls so i'm guessing they want this url to be represented
