### ISSUE TITLE
Frontend JWT handling

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/cmsch#255]
> A frontenden megnyomok egy Login buttont, amely meghívja a backenden a control/login route-ot, amely továbbít a megfelelő authsch route-ra, ott megtörténik az autorizáció, az visszavezet a megadott redirect url-re (pl. localhost:8080/control/loggedin idk a lényeg, hogy a backendre vigyen), és ott a backend készít egy jwt-t, amit lepasszol a frontendnek egy redirecttel a /auth/success oldalra (a jwt token pedig egy queryparamban utazik), a frontend fogja, lementi a kapott tokent, és minden további kérésben az Authorization headerben tolja át a backendre `Bearer ${jwtToken}` formában.

**Comment by Gerviba** [comment]
Currently it redirects the client into the frontend context root with a jwt query param (`/?jwt=urlEncodedJwtToken`). Should I change this?

**Comment by triszt4n** [comment]
Nope, it's better, my logic has right now an extra (unnecessary) frontend redirect, which could be omitted, if we check on the index page, if the query params have a jwt key. Gonna mend it today

**Comment by triszt4n** [comment]
*Tuesday
