### ISSUE TITLE
Add markdown WYSIWYG editor for admin panels

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#283]
subtask of #261

**Comment by triszt4n** [comment]
I'm currently researching how the WYSIWYG should be implemented, there's [a list here](https://github.com/stars/triszt4n/lists/wysiwyg-repos) with the repos I've taken a look at, but these use another form other than converting to markdown (JSON). If we really need to convert to markdown, there are solutions for that too (you can see a working one [in my Önlab project](https://github.com/triszt4n/remark/blob/master/client/src/pages/explore/components/RemarkEditor.tsx) too).

All in all, you can count on me working on this issue.
