### ISSUE TITLE
Bucketlist pages

### ISSUE THREAD

**Issue by berenteb** [kir-dev/cmsch#32]
List page:
- Name and status (if API support is available)

BucketList entity page:
- name, description etc.
- submit field

**Comment by berenteb** [comment]
FileUpload component with Chakra (not native):
https://github.com/chakra-ui/chakra-ui/issues/457

**Comment by Tschonti** [comment]
Allowed submission extensions: png, jpg, jpeg, gif (case insensitive)

**Comment by Tschonti** [comment]
Another FileUpload component with Chakra (not native):
https://github.com/PedroDBFlores/chakra-ui-file-picker
