### ISSUE TITLE
Investigate the webpack warning about the react-simple-code-editor package

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/cmsch#370]
WARNING in ./node_modules/react-simple-code-editor/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '.\node_modules\react-simple-code-editor\src\index.tsx' file: Error: ENOENT: no such file or directory, open '.\node_modules\react-simple-code-editor\src\index.tsx'

**Comment by DannySS123** [comment]
This is probobly the most accurate descreption I could find:

![image](https://user-images.githubusercontent.com/65909866/213928236-751683db-bf2b-4e62-bcc6-f9b06678293a.png)

I checked but didn't find anything related to this on the react-simple-code-editor github.

So until they fix it, the only solution is to supress the warning somehow. I found 2 solutions:

- in .env: 
 GENERATE_SOURCEMAP=false
 If there are no generated source maps, then there won't be errors about them. But I don't know if it's a good idea to disable generating sourcemaps.

- This is the more sophisticated approach.
![image](https://user-images.githubusercontent.com/65909866/213929069-81613aa2-0e04-41dc-ad18-5b0ce15c059d.png)
Kinda sus that the example code is exactly what we need...

@berenteb, @Tschonti what do you think?

**Comment by Tschonti** [comment]
Don't disabled generating sourcemaps (TIL what sourcemaps are [https://css-tricks.com/should-i-use-source-maps-in-production/](https://css-tricks.com/should-i-use-source-maps-in-production/) (first few paragraphs))

ignoring the warning seems like the best idea, or open an issue on their repo 😄

**Comment by DannySS123** [comment]
Nevermind, just updating the package seems to solve it 😃
