### ISSUE TITLE
Small UI changes

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#382]
- [x] üdvözlünk -> pattern | home.welcomeMessage (text), home.content (markdown)
- [x] force dark mode | style.forceDarkMode
- [x] footer small edition | app.minimalisticFooter
- [x] logo cannot be changed | style.lightLogoUrl, style.darkLogoUrl
- [x] login menu | login.onlyBmeProvider, login.langLoginMenu
- [ ] font is broken after some site changes
- [x] backround should not depend content height rather viewport and scroll with the browser

**Comment by berenteb** [comment]
IDK about the font
