### ISSUE TITLE
Profile page does not reset on view reopen

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#396]
It is fetched when viewed first. Must refect on view reopen. (not just page refresh)

**Comment by Gerviba** [comment]
and please verify that it is a real problem, im not sure

**Comment by Tschonti** [comment]
It is a real problem

**Comment by Tschonti** [comment]
I can't test it, but maybe passing the { refetchOnMount: "always"  } option to the currentUser query could solve it? It's weird, because this doesn't happen with the other queries, and we don't use that option there either. I guess I don't quite understand how React Query works 😄

**Comment by Gerviba** [comment]
Eg. in /tasks we fetch the api every time cuz i saw the status change when i submitted a task
