### ISSUE TITLE
G7 kickoff meeting

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#423]
- [x] F: Profile display map
- [x] F: Profile display image
- [x] F: UX/UI Design WS
- [x] B: Tocken collector for groups
- [x] F/B: Anonim help kérő cucc + pipa doboz a nem anonimhoz
- [x] F/B: Nyelvi fájl bacendről
- [x] B: Felhasználó emailjének a kijelzése is
- [x] F: Több helyre markdownos komponens (pl: warning boxokba), minden lap tetejére és aljára.
- [x] B: Export/import
- [x] B: Rendezvény kijelzése, staging jelzése
- [x] B: Aktív userek jelzése
- [x] B: Komponens overview
- [x] F: Markdown extra elemek, pl: gomb, más fajta kép, doboz, 
- [x] B/F: Időzóna egyeztetés
- [x] OPS: Erőforrás kérés, domains
- [x] OPS: Full deployment kimentése yaml-be
- [x] OPS: Vercel rendberakása
- [x] F/B: Kezdőlap komponens állítható program / hírek menü
- [x] F: Kiemelt hír szebben
- [x] F: Hír és event képeinek szebb kijelzése
- [x] B: Térkép testreszabása
- [x] F/B: Híre és események 2 oszlop / 1 oszlop mód
- [x] F/B: Warning komponens frissítése idpnként
- [x] F: Dropdown színe
- [x] F: tipográfia
- [x] F: favikon
- [x] egyéb előjövő hibák

**Comment by Gerviba** [comment]
- F: Hide container backround for home component parts (welcome message, counter, video) if an option is enabled

**Comment by Gerviba** [comment]
F: Menu texts and icons (eg. facebook logo / instagram logo)

**Comment by Gerviba** [comment]
F: Loading screen smoothness

**Comment by berenteb** [comment]
Profile display image where?
