### ISSUE TITLE
Display task name on task rate screen

### ISSUE THREAD

**Issue by Isti01** [kir-dev/cmsch#699]
The name of the task should be displayed on:
- task rate entity screen (Értékelések)
- submitted task entity screen (Nyers beadások)

**Comment by albi005** [comment]
![2024-06-01T14:42:02,228916618+02:00](https://github.com/kir-dev/cmsch/assets/22728934/bf7b802c-40f3-4bab-a308-e945d7101d21)

Implemented in https://github.com/kir-dev/cmsch/commit/d27f0dc0944e5d7dd6e5ae91c1138add0c9466dd
