### ISSUE TITLE
Service layer with error pages

### ISSUE THREAD

**Issue by berenteb** [kir-dev/cmsch#72]
Create a service layer to handle errors globally. Create a universal error page to handle these errors.
Idea: display a large error or sad icon with the erorr message (centered of course)!

**Comment by berenteb** [comment]
Since every API call will use this, create it carefully! There will be an issue to change every single API request to use this.

**Comment by berenteb** [comment]
When you catch something, I think it would be good to have a prop to switch strict mode. In strict mode, the error page won't be displayed, and the warning is thrown away.

**Comment by triszt4n** [comment]
> In strict mode, the error page won't be displayed, and the warning is thrown away.

I guess you meant: When it's NOT in strict mode... 

😃
