### ISSUE TITLE
Unauthorized API response

### ISSUE THREAD

**Issue by berenteb** [kir-dev/cmsch#80]
I was trying out the profile API to test the Authentication. I deleted the JSESSIONID to see what happens (I am planning to log the user out if the profile API gives back anything but the profile data, since the session ID is invalid). I got a HTML back, and had to typecheck the axios res.data if it is an object. As I remember the backend redirects to /login, but this will not work with axios AFAIK. The network tab shows a redirect to /login, but the app won't handle that route, because it redirected the axios request (if that's possible)

My suggestion is to give back a status code and we will handle that.

**Comment by Gerviba** [comment]
This issue is fixed
