### ISSUE TITLE
Riddle, riddle category presentation layer

### ISSUE THREAD

**Issue by Gerviba** [kir-dev/cmsch#9]
- list riddles (category)
  - response: [{"id": Int, "title": String, "nextRiddle": Int?, "completed": Int, "total": Int}]
  - endpoint: GET /api/riddle
- get a riddle :riddleId
  - response: {"imageUrl": String, "title": String, "hint": String?, "solved": true}
  - endpoint: GET /api/riddle/:riddleId
- get a hint :riddleId
  - response: {"hint": String}
  - endpoint: PUT /api/riddle/:riddleId/hint
- submit riddle :riddleId
  - body: {"solution": String}
  - response: {"status": enum {CORRECT, WRONG}, "nextId": Int?}
  - endpoint: POST /api/riddle/:riddleId
  - correct && nextId null -> done

**Comment by SepsiLaszlo** [comment]
I think issue #31 is identical to this.
